rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.3
  - jruby-1.7.22
  - jruby-9.0.1.0
gemfile:
  - gemfiles/Gemfile.activerecord-2.3.x
  - gemfiles/Gemfile.activerecord-3.0.x
  - gemfiles/Gemfile.activerecord-3.1.x
  - gemfiles/Gemfile.activerecord-3.2.x
  - gemfiles/Gemfile.activerecord-4.0.x
  - gemfiles/Gemfile.activerecord-4.1.x
  - gemfiles/Gemfile.activerecord-4.2.x
matrix:
  exclude:
    - rvm: jruby-9.0.1.0
      gemfile: gemfiles/Gemfile.activerecord-2.3.x
    - rvm: jruby-9.0.1.0
      gemfile: gemfiles/Gemfile.activerecord-3.0.x
    - rvm: jruby-9.0.1.0
      gemfile: gemfiles/Gemfile.activerecord-3.1.x
    - rvm: jruby-9.0.1.0
      gemfile: gemfiles/Gemfile.activerecord-3.2.x
    - rvm: jruby-9.0.1.0
      gemfile: gemfiles/Gemfile.activerecord-4.0.x
    - rvm: jruby-1.7.22
      gemfile: gemfiles/Gemfile.activerecord-2.3.x
    - rvm: jruby-1.7.22
      gemfile: gemfiles/Gemfile.activerecord-3.0.x
    - rvm: jruby-1.7.22
      gemfile: gemfiles/Gemfile.activerecord-3.1.x
    - rvm: jruby-1.7.22
      gemfile: gemfiles/Gemfile.activerecord-3.2.x
    - rvm: jruby-1.7.22
      gemfile: gemfiles/Gemfile.activerecord-4.0.x
    - rvm: 2.2.3
      gemfile: gemfiles/Gemfile.activerecord-2.3.x
    - rvm: 2.2.3
      gemfile: gemfiles/Gemfile.activerecord-3.0.x
    - rvm: 2.2.3
      gemfile: gemfiles/Gemfile.activerecord-3.1.x
    - rvm: 2.2.3
      gemfile: gemfiles/Gemfile.activerecord-3.2.x
    - rvm: 2.2.3
      gemfile: gemfiles/Gemfile.activerecord-4.0.x
    - rvm: 2.1.5
      gemfile: gemfiles/Gemfile.activerecord-2.3.x
    - rvm: 2.1.5
      gemfile: gemfiles/Gemfile.activerecord-3.0.x
    - rvm: 2.1.5
      gemfile: gemfiles/Gemfile.activerecord-3.1.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.activerecord-2.3.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.activerecord-4.2.x
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.activerecord-4.2.x
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.activerecord-4.1.x
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.activerecord-4.0.x
