rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.2
gemfile:
  - gemfiles/Gemfile.activerecord-3.0.x
  - gemfiles/Gemfile.activerecord-3.1.x
  - gemfiles/Gemfile.activerecord-3.2.x
  - gemfiles/Gemfile.activerecord-4.0.x
  - gemfiles/Gemfile.activerecord-4.1.x
matrix:
  exclude:
    - rvm: 2.2.2
      gemfile: gemfiles/Gemfile.activerecord-3.0.x
    - rvm: 2.2.2
      gemfile: gemfiles/Gemfile.activerecord-3.1.x
    - rvm: 2.2.2
      gemfile: gemfiles/Gemfile.activerecord-3.2.x
    - rvm: 2.2.2
      gemfile: gemfiles/Gemfile.activerecord-4.0.x
    - rvm: 2.1.2
      gemfile: gemfiles/Gemfile.activerecord-3.0.x
    - rvm: 2.1.2
      gemfile: gemfiles/Gemfile.activerecord-3.1.x
    - rvm: 2.1.2
      gemfile: gemfiles/Gemfile.activerecord-3.0.x
    - rvm: 2.1.2
      gemfile: gemfiles/Gemfile.activerecord-3.1.x
